server:
  port: 8080
  servlet:    session:      cookie:        name: OAUTH2SESSION
security:  oauth2:    client:      client-id: client1
      client-secret: 123456
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
    resource:      jwt:        key-uri: http://localhost:9000/oauth/token_key