server:
  port: 8080
  
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      grant-type: password
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token
      user-info-uri: http://localhost:9000/user
    authorization:
      check-token-access: http://localhost:9000/oauth/check_token