#数据分片
sharding:
  jdbc:
    datasource:
      names: db0,db1
      db0:
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://10.231.8.163:3306/RAWWANT?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
         username: RAWuser
         password: dUDEbt9F
      db1:
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://10.231.8.164:3306/RAWWANT?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
         username: DWuser
         password: ubH3zmza
    config:      props:        sql.show: true
      sharding:        default-database-strategy:          inline:            sharding-column: id
            algorithm-expression: db$->{id % 2}
        tables:          t_user:
            actual-data-nodes: db$->{0..2}.t_user_$->{0..2} 
            table-strategy:              inline:                sharding-column: id
                algorithm-expression: t_user_$->{id % 2}
#读写分离                 master-slave-rules:
          ds0: 
             master-data-source-name: aaa
             slave-data-source-names: bbb                        
            