#数据分片
sharding:
  jdbc:
    datasource:
      names: db0,db1,db2
      db0:
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
         username: root
         password: Welcome1
      db1:
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
         username: root
         password: Welcome1
      db2:
         type: com.zaxxer.hikari.HikariDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         jdbc-url: jdbc:mysql://localhost:3306/db0?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
         username: root
         password: Welcome1
    config:      props:        sql.show: true
      sharding:        default-database-strategy:          inline:            sharding-column: id
            algorithm-expression: db$->{id % 3}
        tables:          t_user:
            actual-data-nodes: db$->{0..2}.t_user_$->{0..2} 
            table-strategy:              inline:                sharding-column: org_code
                algorithm-expression: t_user_$->{org_code % 3}
#读写分离                 master-slave-rules:
          ds0: 
             master-data-source-name: aaa
             slave-data-source-names: bbb                        
            